# Generated by Django 5.2.4 on 2025-07-26 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campionato',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Nazionalita',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arbitro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dirigente',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dirigente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Giornata',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('campionato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giornate', to='league.campionato')),
            ],
            options={
                'unique_together': {('numero', 'campionato')},
            },
        ),
        migrations.AddField(
            model_name='campionato',
            name='nazionalita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campionati', to='league.nazionalita'),
        ),
        migrations.CreateModel(
            name='Partita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('risultato', models.CharField(blank=True, max_length=10, null=True)),
                ('data', models.DateTimeField()),
                ('stadio', models.CharField(max_length=100)),
                ('gol_casa', models.IntegerField(blank=True, null=True)),
                ('gol_ospite', models.IntegerField(blank=True, null=True)),
                ('campionato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partite', to='league.campionato')),
                ('giornata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partite', to='league.giornata')),
            ],
        ),
        migrations.CreateModel(
            name='Referto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referto', models.DateField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referti', to='league.arbitro')),
                ('partita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referti', to='league.partita')),
            ],
        ),
        migrations.CreateModel(
            name='Responsabile',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsabile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Squadra',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('data_fondazione', models.DateField(blank=True, null=True)),
                ('stadio', models.CharField(max_length=100, null=True)),
                ('capacita_stadio', models.IntegerField(null=True)),
                ('citta', models.CharField(max_length=100, null=True)),
                ('campionato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squadre', to='league.campionato')),
            ],
        ),
        migrations.AddField(
            model_name='partita',
            name='squadra_casa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partite_casa', to='league.squadra'),
        ),
        migrations.AddField(
            model_name='partita',
            name='squadra_ospite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partite_ospite', to='league.squadra'),
        ),
        migrations.CreateModel(
            name='Classifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posizione', models.IntegerField()),
                ('punti', models.IntegerField(default=0)),
                ('gol_fatti', models.IntegerField(default=0)),
                ('gol_subiti', models.IntegerField(default=0)),
                ('differenza_reti', models.IntegerField(default=0)),
                ('partite_giocate', models.IntegerField(default=0)),
                ('partite_vinte', models.IntegerField(default=0)),
                ('partite_pareggiate', models.IntegerField(default=0)),
                ('partite_perse', models.IntegerField(default=0)),
                ('campionato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifiche', to='league.campionato')),
                ('squadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifiche', to='league.squadra')),
            ],
            options={
                'ordering': ['posizione'],
                'unique_together': {('campionato', 'squadra')},
            },
        ),
    ]
