# Generated by Django 5.2.4 on 2025-07-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitro',
            name='otp_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dirigente',
            name='otp_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='responsabile',
            name='otp_configured',
            field=models.BooleanField(default=False),
        ),
    ]
